Issue #14 & #26 and fixes
AdExNetwork/adex-protocol pull request #63
Opened 2020-10-14 11:33 UTC by elpiel

2020-10-28 14:33 UTC, samparsky approved these changes

2020-11-13 09:59 UTC, IvoPaunov commented on components/validator-stack.md
> +##### 1. Was this Authentication toke intended for this validator?
token

2020-11-13 09:59 UTC, IvoPaunov commented on components/validator-stack.md
> +* `address` - string - "0x" prefixed address (TODO: what is it used for?)
maybe remove the TODO?

2020-11-13 11:12 UTC, IvoPaunov commented on components/validator-stack.md
> +    As of October 2020 the Rust implementation of Sentry is lacking behind the JavsScript implementation.
JavsScript typo

2020-11-13 11:17 UTC, IvoPaunov requested changes
see the comments - some typos

2020-11-13 12:53 UTC, elpiel commented on components/validator-stack.md
> +##### 1. Was this Authentication toke intended for this validator?
Fixed, tnx!

2020-11-13 12:53 UTC, elpiel commented on components/validator-stack.md
> +* `address` - string - "0x" prefixed address (TODO: what is it used for?)
Fixed, tnx!

2020-11-13 12:53 UTC, elpiel commented on components/validator-stack.md
> +    As of October 2020 the Rust implementation of Sentry is lacking behind the JavsScript implementation.
Fixed, tnx!

2020-11-13 12:55 UTC, IvoPaunov approved these changes
see the comments - some typos

2020-11-13 13:38 UTC, merged